### ISSUE TITLE
Code/Dataset release & licensing

### ISSUE THREAD

**Issue by antoinemacia** [scene-verse/SceneVerse#1]
Really exciting work, thank you! 

Interested to know what are your plans in regards to exposing the dataset, training instructions and/or pre-trained model? 

Thanks again!

**Comment by Buzz-Beater** [comment]
Thanks for the interest! And yes we plan to release both processed data (both in pre-extracted features as well as preprocessing code for 3D scene datasets), training instructions, as well as pre-trained checkpoints shortly (as it is under review). Stay tuned!!!

**Comment by gleize** [comment]
Hi. Thanks for the great work.

Do you have an ETA regarding the release ? (just to get a sense if it's going in a few days, or a few weeks / months).

**Comment by Buzz-Beater** [comment]
Yes, we are planning to announce the data after the CVPR decision is released. So this will be the beginning of March, stay tuned!

**Comment by EricLee0224** [comment]
Hi, @Buzz-Beater 
Very promising work! Do you have any plan about release the data recently? Thanks.

**Comment by ybgdgh** [comment]
Hi, @Buzz-Beater I also want to know when you will release the data. Thanks.

**Comment by Buzz-Beater** [comment]
Hi, thank you all for your interest and patience! We have just released SceneVerse data, check out the README for downloading instructions! We will release the training/inference codes shortly, stay tuned!

**Comment by Boyu-Mi** [comment]
Hi, @Buzz-Beater 
Thanks for the impressive work. Would you release the scene graph data mentioned in paper?

**Comment by Buzz-Beater** [comment]
Hi, @Boyu-Mi 
Scene graphs and the data generation process are currently not within the data release plan. We intend to iterate on the data generation process based on feedback from the current data release. We will release the generation pipeline and scene graphs in the future after refinement.

**Comment by Buzz-Beater** [comment]
As we have gradually released data and train/inference codes, we are closing this issue for now, feel free to raise any new issues regrading SceneVerse :-)
