### ISSUE TITLE
Point Cloud Alignment Code

### ISSUE THREAD

**Issue by lnbxldn** [scene-verse/SceneVerse#11]
Hi, SceneVerse is a great dataset. Although your point cloud alignment method has been explained in the paper, I still haven't found an effective way to align my custom data with your point cloud. Can you provide the corresponding code?Thx!

**Comment by Buzz-Beater** [comment]
Yes, we plan to release the code for aligning codes, however, we are undergoing an internal code review, so we will try to figure out a way to give some code snippets as an alignment example in the coming weeks.

**Comment by yixchen** [comment]
Hi, we have released the instructions `preprocess/README.md` and an example script for data preprocessing and alignment in `preprocess/rscan.py`. Check out!

**Comment by Buzz-Beater** [comment]
Closing issue as we have already provided the alignment code, feel free to re-open this thread if there is any issue.
