### ISSUE TITLE
Download link error！

### ISSUE THREAD

**Issue by jyydlut** [scene-verse/SceneVerse#12]
SceneVerse request
“SceneVerse request”表单已不再接受回复。
如果您认为不应该出现这种情况，请尝试与表单所有者联系。
please check the link and repair it！

**Comment by Buzz-Beater** [comment]
Thanks for pointing it out. As the original hosting server is experiencing several errors, we are transferring all files to another publicly available position. The transfer might take 3-5 days, we will adjust the error in the download link accordingly. Sorry for the trouble.

**Comment by Buzz-Beater** [comment]
Hi, we have already fixed the download link error, you can access the request form from either the project website or the link from this repo. Remember to clear your cache in case when using the link from the website though :-)
