### ISSUE TITLE
Scene graph generation pipeline code

### ISSUE THREAD

**Issue by zubair-irshad** [scene-verse/SceneVerse#16]
Hi authors, 

Thanks for the great work! Do you plan to release scene graph generation pipeline code or could point to the repo you used for your scene graph generation? Thank you!

**Comment by Buzz-Beater** [comment]
Hi, we have the plan for releasing scene graph generation codes but are under an internal code review, so the model codes including training / scene-graph generation should be gradually coming out in the following weeks just like the preprocessing codes. Thanks for the patience.

**Comment by albertcity** [comment]
> Hi, we have the plan for releasing scene graph generation codes but are under an internal code review, so the model codes including training / scene-graph generation should be gradually coming out in the following weeks just like the preprocessing codes. Thanks for the patience.

May I ask when the scene-graph generation code will  be releasing? Tkx :)

**Comment by Yebulabula** [comment]
Hi, I am also interested in when the scene-graph generation code will be released.

**Comment by yixchen** [comment]
Hi, we have released the scripts for scene graph generation. See [here](https://github.com/scene-verse/SceneVerse/tree/main/preprocess/ssg#readme). Feedback and PRs are welcome.

**Comment by Buzz-Beater** [comment]
Closing this issue as we have already provided the generation code, feel free to re-open it if there is any issue.
