### ISSUE TITLE
Language generation pipeline code

### ISSUE THREAD

**Issue by yu3jun** [scene-verse/SceneVerse#19]
Hi authors,  

Thanks for the great work ! 

I'm glad to know that you have the plan for releasing scene graph generation codes, and I'm looking forward to it.
But I wonder do you plan to release language generation pipeline codes including how to use the constructed 3d scene graph?

Thank you !

**Comment by Buzz-Beater** [comment]
Hi we've finished the scene-graph generation code, please check it out. In terms of language generation, we followed the pseudo code to generate language, we tried to make it easy to follow, if there is extra need, we will try wrapping up the generation code as well :-)

**Comment by Buzz-Beater** [comment]
Closing issue as we have already released the data, feel free to re-open it!
