### ISSUE TITLE
Where is scannet_607_bert-base-uncased_id.pth

### ISSUE THREAD

**Issue by WinterCodeForEverything** [scene-verse/SceneVerse#22]
Thanks for your excellent work, could you please tell me how to get scannet_607_bert-base-uncased_id.pth for pre-train? BTW, when will you release all pre-trained checkpoints?
<img width="1143" alt="Screenshot 2024-09-02 at 15 06 23" src="https://github.com/user-attachments/assets/ff9e99d8-e6ad-4d3e-b38b-4ab612643a1f">

**Comment by Buzz-Beater** [comment]
Hi, I have added the text embeddings in the G-Drive link under ```Checkpoints```, all model checkpoints will come out next week, tx for waiting!

**Comment by Buzz-Beater** [comment]
Procrastinated for the checkpoint release and also attending ECCV this week so probably for another week :-<

**Comment by Buzz-Beater** [comment]
Hi we have already added the links to checkpoints in ```TRAIN.md```, try checking them out and let me know if there is any issue :-)

**Comment by Buzz-Beater** [comment]
Hi, you should be seeing it in the ```Checkpoints``` directory now under ```607_text_embeddings```, I made a careless mistake and created two ```Checkpoints``` directory under the same gdrive link, now they are merged :-)
