### ISSUE TITLE
G-drive data

### ISSUE THREAD

**Issue by KongFulu** [scene-verse/SceneVerse#23]
Your data stored in G-drive is no longer valid, can you repost it, or I will request it to your email

**Comment by Buzz-Beater** [comment]
Hi, we have updated the g-drive link as google recently had policy updates for education workspaces which forbid us from using the old one. So if you are using an old link (before June maybe), you can try resubmitting the request form and using the updated link. Let me know if there is any issue :-)

**Comment by KongFulu** [comment]
Thank you for your help, I have a question, the link in the Data Download in the github page has failed, and the link in the News can be applied, are these two data the same. I also have a question, in the README.md you are using CUDA 11.8 but in the requirements.txt you are using 12.1, which one should I use
![image](https://github.com/user-attachments/assets/9285808f-e6a5-4ab9-9a4f-593734be3863)

**Comment by Buzz-Beater** [comment]
Nice catch, we will update the README to be compatible with the ```requirements.txt```. Meanwhile, you can use CUDA 12.1:-)
