### ISSUE TITLE
Issue in Evaluation

### ISSUE THREAD

**Issue by Yangl1nFeng** [scene-verse/SceneVerse#26]
FileNotFoundError: Cannot find pytorch_model.bin in /SceneVerse-main/results/FinalOVPretrain_b64_Pretrain_scanrefer_no_note/2024-10-10-09:23:20.509828/ckpt/best.pth. 

Hello! I don't understand why I have trained correctly but got the .safetensors model instead of the .bin model. I don't know if there is something wrong?

**Comment by Buzz-Beater** [comment]
Hi, can you try checking if the ```transformers``` package's version matches the provided one in the ```requirements.txt```? It could be updated by the Huggingface Transformers repo. Meanwhile, you can also try checking out the provided checkpoints in ```TRAIN.md``` to see if the pipeline walks through :-)
