### ISSUE TITLE
scannet scene graph

### ISSUE THREAD

**Issue by DevXiaoYan** [scene-verse/SceneVerse#4]
Thank you for publishing such a useful dataset. May I ask how to obtain scene graph annotation data from the scannet dataset. In the refer folder, only the folder named sr3d has anchor ids.

**Comment by Buzz-Beater** [comment]
Hi, scene graphs in SceneVerse are not within the current release plan, the sr3d ones are from the original paper. Stay tuned!

**Comment by yixchen** [comment]
Hi, we have released the scripts for scene graph generation. See [here](https://github.com/scene-verse/SceneVerse/tree/main/preprocess/ssg#readme). Feedback and PRs are welcome.

**Comment by Buzz-Beater** [comment]
Closing this issue as we have already provided related codes and instructions, feel free to re-open this thread if anything comes up :-)
