### ISSUE TITLE
The view-dependent object relationships determination

### ISSUE THREAD

**Issue by ZCMax** [scene-verse/SceneVerse#6]
As the paper state: `Horizontal relationships describe the proximity relations like in front of, next to, behind, etc. Relationships like left, right are contextually dependent on a reference view, where another anchor object is utilized to establish the view direction. The distance between the two objects is also calculated to describe whether the objects are far or near in space.` 
I can understand that for `left` and `right` object relationship, it's needed to provide the reference view. My question is that does the object relationship like `in front of` and `behind` not rely on the reference view?

**Comment by yixchen** [comment]
Hi, 

The `in front of` and `behind` are related to the reference view in our relationship determination. Imagine one object is `in front of` another object under one view direction, their relationship could be totally different, i.e., `behind`, if you see them from the opposite direction (another side of the room). While this may not always be true, as such relationships are also related to the object orientation (e.g., `in front of` the TV), we treat them as view-dependent in the currently released data.

**Comment by yixchen** [comment]
1. Yes.
2. The default view direction is along the `+y` axis (z-up) in the aligned scene point clouds that we provide in SceneVerse.

**Comment by ZCMax** [comment]
After checking the annotations in scannet referal dataset, I found the for the reference view information, it demonstrates like "facing the bed". However, how is such statement generated? Or what is the definitation of "facing"? Since I'm working on the egocentric perception task, so I want to know more details about the possible observation information. thanks

**Comment by yixchen** [comment]
Hi, we have released the scripts for scene graph generation. See [here](https://github.com/scene-verse/SceneVerse/tree/main/preprocess/ssg#readme). Feedback and PRs are welcome.

**Comment by Buzz-Beater** [comment]
Closing this issue as we have already provided related codes and instructions, feel free to re-open this thread if there is any issue :-)
