### ISSUE TITLE
Version of the HM3D semantic dataset

### ISSUE THREAD

**Issue by ybgdgh** [scene-verse/SceneVerse#8]
Hi, I want to know which version of the hm3d semantic datasets you used in your work? Since now the hm3d has the v0.2 semantic anno, maybe if we use the habitat simulator, we need to make sure the object_id is the same as the targer_id in your datasets? Thanks.

**Comment by Buzz-Beater** [comment]
Hi, we have already provided the mapping script and instructions in the README.md, hope this helps your project:-)

**Comment by Buzz-Beater** [comment]
As we have already provided the mapping, closing this issue for now.
